root = "."
tmp_dir = "runtime/air"

[build]
cmd = "go build -o ./runtime/air/main main.go"
bin = "runtime/air/main"
watch_dir = "."
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
exclude_dir = ["runtime", "vendor"]

[log]
time = true
