services:
  todof-go:
    build:
      target: dev
      context: .
      dockerfile: Dockerfile
    image: ${NSC_NAME_CONTAINER_APP}:latest
    container_name: ${NSC_NAME_CONTAINER_APP}
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - todof-db
    networks:
      - todof-net
      - traefik-nseven

  todof-db:
    image: postgres:16
    container_name: todof-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todof-db-data:/var/lib/postgresql/data
    networks:
      - todof-net
      - traefik-nseven

networks:
  todof-net:
    name: todof-net
    driver: bridge
  traefik-nseven:
    external: true

volumes:
  todof-db-data: