services:
  todof-go-prod:
    build:
      target: prod
      context: ..
      dockerfile: docker/Dockerfile
    container_name: todof-go-prod
    image: todof-go:prod
    volumes:
      - ../:/app
    env_file:
      - ../.env
    networks:
      - traefik-nseven
      - todof
    depends_on:
      - todof-db-prod

  todof-db-prod:
    image: mongo:7
    container_name: todof-db-prod
    restart: unless-stopped
    volumes:
      - todof-db-prod-data:/data/db
      - ../docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - traefik-nseven
      - todof

networks:
  traefik-nseven:
    external: true
  todof:
    driver: bridge

volumes:
  todof-db-prod-data: