name: todof-prod
services:
  todof-go-prod:
    build:
      target: prod
      context: ..
      dockerfile: docker/Dockerfile
    container_name: todof-go-prod
    image: todof:prod
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-nseven"
      - "traefik.http.routers.todof-go-prod.rule=${HOST_TRAEFIK}"
      - "traefik.http.routers.todof-go-prod.entrypoints=websecure"
      - "traefik.http.routers.todof-go-prod.tls=true"
      - "traefik.http.routers.todof-go-prod.tls.certresolver=le"
      - "traefik.http.services.todof-go-prod.loadbalancer.server.port=${PORT}"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    networks:
      - traefik-nseven
      - todof
    depends_on:
      - todof-db-prod

  todof-db-prod:
    image: mongo:7
    container_name: todof-db-prod
    restart: unless-stopped
    volumes:
      - todof-db-prod-data:/data/db
      - ../docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - traefik-nseven
      - todof

networks:
  traefik-nseven:
    external: true
  todof:
    driver: bridge

volumes:
  todof-db-prod-data: