name: todof-${APP_ENV}
services:
  prod:
    build:
      target: ${APP_ENV}
      context: ..
      dockerfile: docker/Dockerfile
    container_name: todof_${APP_ENV}
    image: todof:${APP_ENV}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-nseven"
      - "traefik.http.routers.todof-go-prod.rule=${HOST_TRAEFIK}"
      - "traefik.http.routers.todof-go-prod.entrypoints=websecure"
      - "traefik.http.routers.todof-go-prod.tls=true"
      - "traefik.http.routers.todof-go-prod.tls.certresolver=le"
      - "traefik.http.services.todof-go-prod.loadbalancer.server.port=${PORT}"
    volumes:
      - ../:/app
    env_file:
      - ../.env
    networks:
      - traefik-nseven
      - todof
    depends_on:
      - db

  db:
    image: mongo:7
    container_name: todof_db${APP_ENV}
    restart: unless-stopped
    volumes:
      - todof-db-prod-data:/data/db
      - ../docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - traefik-nseven
      - todof

  redis:
    image: redis:7
    container_name: todof_redis${APP_ENV}
    restart: unless-stopped
    networks:
      - todof

networks:
  traefik-nseven:
    external: true
  todof:
    driver: bridge

volumes:
  todof-db-prod-data: