// Package doc Code generated by swaggo/swag. DO NOT EDIT
package doc

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/login": {
            "post": {
                "description": "Authentification d’un utilisateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Authentifier un utilisateur",
                "parameters": [
                    {
                        "description": "DTO d'authentification utilisateur",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserLoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Connexion réussie",
                        "schema": {
                            "$ref": "#/definitions/doc.ErrorModel"
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "$ref": "#/definitions/doc.ErrorModel"
                        }
                    },
                    "500": {
                        "description": "Erreur d'authentification",
                        "schema": {
                            "$ref": "#/definitions/doc.ErrorModel"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Création d’un nouvel utilisateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Créer un utilisateur",
                "parameters": [
                    {
                        "description": "DTO d'inscription utilisateur",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.UserCreateDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "1"
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "$ref": "#/definitions/doc.ErrorModel"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "$ref": "#/definitions/doc.ErrorModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.UserCreateDto": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "auth.UserLoginDto": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "doc.ErrorModel": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API todo-formation",
	Description:      "Une API pour créer des todo avec utilisateurs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
