basePath: /api/v1
definitions:
  auth.UserCreateDto:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  auth.UserLoginDto:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  doc.ErrorModel:
    properties:
      data:
        type: string
      error:
        type: string
      message:
        type: string
    type: object
host: todof.local
info:
  contact: {}
  description: Une API pour créer des todo avec utilisateurs
  title: API todo-formation
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: Authentification d’un utilisateur
      parameters:
      - description: DTO d'authentification utilisateur
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.UserLoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: Connexion réussie
          schema:
            $ref: '#/definitions/doc.ErrorModel'
        "400":
          description: Erreur de validation
          schema:
            $ref: '#/definitions/doc.ErrorModel'
        "500":
          description: Erreur d'authentification
          schema:
            $ref: '#/definitions/doc.ErrorModel'
      summary: Authentifier un utilisateur
      tags:
      - user
  /user/profil:
    get:
      consumes:
      - application/json
      description: 'Récupére le profil de l''utilisateur connecté via le token utilisé
        dans le header (pour try out : clique sur le cadenas, puis tape Bearer "ton
        token")'
      produces:
      - application/json
      responses:
        "200":
          description: Profil utilisateur récupéré avec succès
          schema:
            $ref: '#/definitions/doc.ErrorModel'
        "401":
          description: Invalide token
          schema:
            $ref: '#/definitions/doc.ErrorModel'
        "500":
          description: Erreur interne
          schema:
            $ref: '#/definitions/doc.ErrorModel'
      security:
      - BearerAuth: []
      summary: Récupérer le profil de l'utilisateur connecté
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: Création d’un nouvel utilisateur
      parameters:
      - description: DTO d'inscription utilisateur
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.UserCreateDto'
      produces:
      - application/json
      responses:
        "204":
          description: "1"
        "400":
          description: Erreur de validation
          schema:
            $ref: '#/definitions/doc.ErrorModel'
        "500":
          description: Erreur interne
          schema:
            $ref: '#/definitions/doc.ErrorModel'
      summary: Créer un utilisateur
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
